feat: module migration to `ai4os-hub` (#51)
* feat: use url from gitsubmodules

* feat: update tests

* fix: relax constraints on Dockerhub image name

* feat: move to ai4os-hub/modules-catalog

* fix: fix weird FastAPI error

without list(...) FastAPI throws weird error
ValueError: [ValueError('dictionary update sequence element #0 has length 1; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]

* feat: prettier errors