fix: fix weird FastAPI error
without list(...) FastAPI throws weird error
ValueError: [ValueError('dictionary update sequence element #0 has length 1; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]